version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
        - echo "getting environment for nodejs"
        - npm install -g mongoose
        - npm install -g mocha
        - npm install
        - echo "end install dependancies"
  pre_build:
    commands:
        - echo "start building" 
  build:
    commands:
        - mocha ./bin/www.js
  post_build:
    commands:
        - echo Build completed on `date`
      # - command
artifacts:
  #files:
    # - app.js
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
