version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
        - echo "getting environment for nodejs"
        - cd React_front
        - npm install -g mongoose
        - npm install -g mocha
        - echo "end install dependancies"
  pre_build:
    commands:
        - echo "start building" 
  build:
    commands:
        - mocha HelloWorld.js
  post_build:
    commands:
        - echo Build completed on `date`
      # - command
artifacts:
  files:
    - HelloWorld.js
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
